2022-05-20
CDDSCLab/Weekly-Group-Meeting-Paper-List pull request #29
Opened 2022-05-20 09:29 UTC by zqyi

add: 2022-05-20-云原生基础架构—Container、Kubernetes

2022-05-22 03:59 UTC, ehds requested changes

2022-05-22 03:59 UTC, ehds commented on meeting-summary/2022-05-20-云原生基础架构—Container、Kubernetes.md
> +1. **Q：**cGroups 是对容器资源上限的描述？那这些资源在不使用时是否会被保留？会不会因为其它进程的占用而导致容器使用不到这些资源的上限。
```suggestion
1. **Q:** cGroups 是对容器资源上限的描述？那这些资源在不使用时是否会被保留？会不会因为其它进程的占用而导致容器使用不到这些资源的上限。
```

2022-05-22 03:59 UTC, ehds commented on meeting-summary/2022-05-20-云原生基础架构—Container、Kubernetes.md
> +   **A：**这些资源不会被保留。会出现资源被占用的情况。例如教研室集群，每位用户都具有最高权限，容器都没有使用资源限制，那么是会相互抢占的。但是，在 PaaS 场景下，容器是由云服务厂商管理的，用户只能访问容器内部。例如对于 64GB 的内存，厂商可以在其上提供 16GB 内存大小的容器供客户使用，这时不会发生资源被占用，但是厂商可以在用户负载的低谷，将这些资源用来运行自己的其它服务。
```suggestion
   **A:** 这些资源不会被保留。会出现资源被占用的情况。例如教研室集群，每位用户都具有最高权限，容器都没有使用资源限制，那么是会相互抢占的。但是，在 PaaS 场景下，容器是由云服务厂商管理的，用户只能访问容器内部。例如对于 64GB 的内存，厂商可以在其上提供 16GB 内存大小的容器供客户使用，这时不会发生资源被占用，但是厂商可以在用户负载的低谷，将这些资源用来运行自己的其它服务。
```

2022-05-22 03:59 UTC, ehds commented on meeting-summary/2022-05-20-云原生基础架构—Container、Kubernetes.md
> +2. **Q：**PID Namespce 的隔离是不是代表着进程会有两个 PID。
```suggestion
2. **Q:** PID Namespce 的隔离是不是代表着进程会有两个 PID。
```

2022-05-22 03:59 UTC, ehds commented on meeting-summary/2022-05-20-云原生基础架构—Container、Kubernetes.md
> +   **A：**是。但是着两个 PID 不是在一个 Namespace 下的，在 Host Namespace 看，进程的 PID 是 20731；但是对于容器内部的进程，其只能看到 Container Namespace，即看到自己的进程号是 1。
```suggestion
   **A:** 是。但是这两个 PID 不是在一个 Namespace 下的，在 Host Namespace 看进程的 PID 是 20731；但是对于容器内部的进程，其只能看到 Container Namespace，即看到自己的进程号是 1。
```

2022-05-23 02:44 UTC, IcePigZDB commented on meeting-summary/2022-05-20-云原生基础架构—Container、Kubernetes.md
> +- 关键词：Kubernetes, Container, 云原生
```suggestion
- 关键词：Kubernetes, Container, Cloud Native
```

2022-05-23 02:50 UTC, IcePigZDB approved these changes
LGTM

2022-05-23 02:57 UTC, ehds approved these changes

2022-05-23 02:57 UTC, ehds commented
LGTM

2022-05-23 02:58 UTC, merged