2022-06-04: vectorization vs compilation
CDDSCLab/Weekly-Group-Meeting-Paper-List pull request #33
Opened 2022-06-04 15:10 UTC by IcePigZDB

Signed-off-by: IcePigZDB <icepigzdb@gmail.com>

### Summary of talk

Date: 2022-06-02

Topic: vectorization vs compilation

Keywords: Execution Engine, Volcano, Vectorization, Compilation

### Format check List

- [ ] Conforming to English specifications especially in `README.md`.
- Capitalize the first letter.
- Use English punctuation with appropriate space.
- ...
- [ ] Remember to add links to reference papers.
- [ ] Make sure the link is accessible.
- Use dash `-` to connect filename rather than space ` `, the latter will casue dead link.
- [ ] Make sure latex formulas display normally, more can be found in [#27](https://github.com/CDDSCLab/Weekly-Group-Meeting-Paper-List/issues/27).

2022-06-05 03:30 UTC, ehds requested changes
rm a.cpp

2022-06-05 03:30 UTC, ehds commented on meeting-summary/2022-06-02-Vectorization-vs-Compilation.md
> +[05] – 参考博文: https://www.one-tab.com/page/LmMkDhRhRWKUxU2bRRJgQA\
[06],
new line

2022-06-06 01:18 UTC, IcePigZDB commented on meeting-summary/2022-06-02-Vectorization-vs-Compilation.md
> +[05] – 参考博文: https://www.one-tab.com/page/LmMkDhRhRWKUxU2bRRJgQA\
All done, ptal.

2022-06-06 01:54 UTC, ehds commented on meeting-summary/2022-06-02-Vectorization-vs-Compilation.md
> +对 Single-Threaded Performance, SIMD, INTRA-QUERY PARALLELIZATION, HARDWARE, Compilation Time 等方面进行了实验对比。得出了一下结论：
`一下结论` -> `以下结论`

2022-06-06 01:54 UTC, ehds commented on meeting-summary/2022-06-02-Vectorization-vs-Compilation.md
> +争对这个问题，Hyper 实现了一种 adaptive compilation，根据不同负载选择不同的执行模式。为此 Hyper 首先实现了基于 vm 的 bytecode 解释执行模式，这种模式需要的编译时间很短，是所有 query 的默认执行模式。Hyper 使用 morsel-driven 的并行执行框架将 pipeline 按照输入切分，分成不同小任务以方便并行和模式切换。Hyper 会
`完成盖 pipeline`  means what?

2022-06-06 03:04 UTC, ehds approved these changes

2022-06-06 03:04 UTC, ehds commented
LGTM

2022-06-06 04:09 UTC, merged